import { defineStore } from 'pinia'

import type { Algorithm } from '@/types'

interface AlgorithmState {
  algorithms: Algorithm[]
}

export const useAlgorithmStore = defineStore('algorithm', {
  state: (): AlgorithmState => ({
    algorithms: [
      {
        name: 'frequency',
        displayName: '频率分析',
        category: '基础统计',
        permissionLevel: 'free',
        description: '基于历史号码出现频次筛选候选，适合作为快速基线。',
        averageCostMs: 860,
        successRate: 0.58,
        enabled: true,
        complexity: '低',
        recommendedScenario: '快速查看近期热号和稳定候选。',
      },
      {
        name: 'hot_cold',
        displayName: '冷热分析',
        category: '基础统计',
        permissionLevel: 'free',
        description: '对热号和冷号做平衡抽取，降低单一频率偏置。',
        averageCostMs: 920,
        successRate: 0.57,
        enabled: true,
        complexity: '低',
        recommendedScenario: '需要热冷号混合参考时使用。',
      },
      {
        name: 'missing',
        displayName: '遗漏分析',
        category: '基础统计',
        permissionLevel: 'free',
        description: '关注长遗漏号码和近期回补概率，适合复盘遗漏周期。',
        averageCostMs: 980,
        successRate: 0.56,
        enabled: true,
        complexity: '低',
        recommendedScenario: '观察长遗漏号码回补机会。',
      },
      {
        name: 'markov',
        displayName: '马尔可夫链',
        category: '马尔可夫',
        permissionLevel: 'vip',
        description: '基于状态转移概率构建下一期候选集。',
        averageCostMs: 1340,
        successRate: 0.6,
        enabled: true,
        complexity: '中',
        recommendedScenario: '关注短期序列转移关系。',
      },
      {
        name: 'adaptive_markov',
        displayName: '自适应马尔可夫',
        category: '马尔可夫',
        permissionLevel: 'vip',
        description: '动态调整转移阶数权重，应对不同窗口走势。',
        averageCostMs: 1680,
        successRate: 0.62,
        enabled: true,
        complexity: '中',
        recommendedScenario: '走势波动较大时做弹性建模。',
      },
      {
        name: 'ensemble',
        displayName: '集成学习',
        category: '机器学习',
        permissionLevel: 'vip',
        description: '融合多个基础模型输出，形成综合候选。',
        averageCostMs: 1880,
        successRate: 0.64,
        enabled: true,
        complexity: '中',
        recommendedScenario: '需要多算法交叉验证。',
      },
      {
        name: 'clustering',
        displayName: '聚类分析',
        category: '机器学习',
        permissionLevel: 'vip',
        description: '按历史号码结构聚类，选择接近中心的候选号码。',
        averageCostMs: 1760,
        successRate: 0.61,
        enabled: true,
        complexity: '中',
        recommendedScenario: '分析号码结构和区间组合。',
      },
      {
        name: 'monte_carlo',
        displayName: '蒙特卡洛模拟',
        category: '机器学习',
        permissionLevel: 'vip',
        description: '通过多轮采样模拟候选稳定性。',
        averageCostMs: 2120,
        successRate: 0.6,
        enabled: true,
        complexity: '中',
        recommendedScenario: '需要观察候选号码稳定性。',
      },
      {
        name: 'lstm',
        displayName: 'LSTM 序列模型',
        category: '深度学习',
        permissionLevel: 'premium',
        description: '使用序列建模捕捉长期趋势变化。',
        averageCostMs: 2860,
        successRate: 0.63,
        enabled: true,
        complexity: '高',
        recommendedScenario: '需要更长周期的序列参考。',
      },
      {
        name: 'transformer',
        displayName: 'Transformer',
        category: '深度学习',
        permissionLevel: 'premium',
        description: '通过注意力机制分析关键期数和号码关系。',
        averageCostMs: 3420,
        successRate: 0.65,
        enabled: true,
        complexity: '高',
        recommendedScenario: '关注关键历史窗口的影响。',
      },
      {
        name: 'gnn',
        displayName: 'GNN 图关系',
        category: '深度学习',
        permissionLevel: 'premium',
        description: '将号码共现关系构造成图，识别关系候选。',
        averageCostMs: 3650,
        successRate: 0.64,
        enabled: true,
        complexity: '高',
        recommendedScenario: '分析号码共现网络。',
      },
      {
        name: 'bayesian',
        displayName: '贝叶斯推理',
        category: '概率与综合',
        permissionLevel: 'vip',
        description: '从先验到后验持续更新候选概率。',
        averageCostMs: 1580,
        successRate: 0.61,
        enabled: true,
        complexity: '中',
        recommendedScenario: '需要概率解释和置信过滤。',
      },
      {
        name: 'high_confidence',
        displayName: '高置信度预测',
        category: '概率与综合',
        permissionLevel: 'premium',
        description: '对候选号码做多轮过滤，只保留高置信结果。',
        averageCostMs: 2480,
        successRate: 0.66,
        enabled: true,
        complexity: '高',
        recommendedScenario: '追求更少但更稳定的候选。',
      },
      {
        name: 'super_predictor',
        displayName: '超级预测器',
        category: '概率与综合',
        permissionLevel: 'premium',
        description: '融合统计、序列、图关系与概率模型的综合输出。',
        averageCostMs: 4200,
        successRate: 0.68,
        enabled: true,
        complexity: '高',
        recommendedScenario: '做最终预测前的综合参考。',
      },
    ],
  }),
  getters: {
    enabledAlgorithms: (state) => state.algorithms.filter((algorithm) => algorithm.enabled),
    recommendedAlgorithms: (state) => state.algorithms.filter((algorithm) => algorithm.enabled).slice(0, 3),
  },
})
